### ISSUE TITLE
Eventually a memory Leak

### ISSUE THREAD

**Issue by philippd1** [EdwardvanRaak/MaterialBarcodeScanner#11]
Hey Edward!
First of all, a great library you did there. But I have some issues. I installed Leak Canary into my app and it says "leaks MaterialBarcodeScannerActivity instance". Does this have to do with ZXing and can you tell me how I could fix this error? Also the scanner doesnt work on Samsung devices like some other guy reported. 
Also sorry for my bad english..I'm from Germany but I do my best :)
Thanks in advance
Philipp

**Comment by EdwardvanRaak** [comment]
Will look into this tommorow

**Comment by philippd1** [comment]
Did you find something? :wave:
