### ISSUE TITLE
Can i get the image after scan?

### ISSUE THREAD

**Issue by PitipongXYZ** [EdwardvanRaak/MaterialBarcodeScanner#18]
Do you have provide that method? 
If yes 
Please let me know how to use
else
Do you have plan to do that?

Thank in advance.

**Comment by TheDorkKnightRises** [comment]
I think issue #5 talks of the same...it's a planned feature

**Comment by PitipongXYZ** [comment]
Oh Thank @TheDorkKnightRises,
