### ISSUE TITLE
Back Pressed

### ISSUE THREAD

**Issue by vitormesquita** [EdwardvanRaak/MaterialBarcodeScanner#2]
When click on android button back de scanner restart. And the camera doesn't appears and it got the black screen.

If I click many times on the button this error happens : 

>  java.lang.RuntimeException: Unable to destroy activity {br.com.beerplusapp.debug/com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.vision.Detector.release()' on a null object reference

**Comment by EdwardvanRaak** [comment]
Does this happen to you with the example project? You can download the apk here:
[a.pomf.cat/ikbvco.apk](url)
