### ISSUE TITLE
Subscriber class com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScanner and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by tatocaster** [EdwardvanRaak/MaterialBarcodeScanner#6]
When I try to start MaterialBarcodeScanner this error occurs, but on on Release Flavour. 

`Subscriber class com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScanner and its super classes have no public methods with the @Subscribe annotation`

**Comment by tatocaster** [comment]
FIXED:  Used EventBus Proguard

`-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
`

Please update readme, in case of this error to refer EventBus documentation..

**Comment by EdwardvanRaak** [comment]
Thanks! I will update the readme for the next release.
